[phases.setup]
cmds = [
  "apt-get update",
  "apt-get install -y gcc g++"
]

[phases.install]
cmds = [
  "pip install --no-cache-dir -r requirements.txt",
  "python -c \"import nltk; nltk.download('punkt')\""
]

[start]
cmd = "gunicorn -c gunicorn.conf.py app:app"